const changeperspectivedata = [
    {
        id: 1,
        title: "Perasaan ini akan berlalu",
        body: "Saya tidak akan merasakan hal seperti ini selama-lamanya. Saya pernah merasakan yang berbeda sebelumnya dan akan merasakan yang berbeda segera.",
        imgUrl: "https://nepho.id/c4omi/img/1.jpg",
    },
    {
        id: 2,
        title: "Saya akan bertahan",
        body: "Saya sudah melewati banyak hal-hal baik suka dan duka di dalam hidup saya dan dalam kemurahan Tuhan dapat bertahan hidup.",
        imgUrl: "https://nepho.id/c4omi/img/2.jpg",
    },
    {
        id: 3,
        title: "Emosiku bukan berdasarkan fakta",
        body: "Emosi-emosi yang saya rasakan memberikan informasi mengenai bagaimana saya merasakan namun emosi-emosiku bukan berdasarkan fakta",
        imgUrl: "https://nepho.id/c4omi/img/3.jpg",
    },
    {
        id: 4,
        title: "Saya dapat mentoleransi hal ini",
        body: "Pergumulan yang saya rasakan dalam batas kekuatan saya. Pencobaan-pencobaan tidak melebihi kekuatanku.",
        imgUrl: "https://nepho.id/c4omi/img/4.jpg",
    },
    {
        id: 5,
        title: "Saya pasti bisa melewati ini",
        body: "Saya akan bertahan bahkan ketika saya tidak bisa tidur sekarang ini.",
        imgUrl: "https://nepho.id/c4omi/img/5.jpg",
    },
    {
        id: 6,
        title: "Segala perkara dapat kutanggung",
        body: "Ada kekuatan misteri yang akan menolongku melewati semua ini.",
        imgUrl: "https://nepho.id/c4omi/img/6.jpg",
    },
    {
        id: 7,
        title: "Situasi yang kualami berbeda",
        body: "Situasi yang dialami berbeda dengan yang dialami dulu dan saya akan baik-baik saja.",
        imgUrl: "https://nepho.id/c4omi/img/7.jpg",
    },
    {
        id: 8,
        title: "Saya ada disini saat ini",
        body: "Saya akan berfokus pada masa kini. Saya tidak cemas akan masa lalu dan kuatir akan masa depan. Kesusahan sehari untuk sehari.",
        imgUrl: "https://nepho.id/c4omi/img/8.jpg",
    },
    {
        id: 9,
        title: "Masa kini adalah anugerah",
        body: "Masa lampau tidak bisa dirubah. Masa depan di tangan Tuhan. Masa kini adalah anugerah. Saya akan bersyukur dan merayakannya.",
        imgUrl: "https://nepho.id/c4omi/img/9.jpg",
    },
    {
        id: 10,
        title: "Akan lebih mudah seiring waktu",
        body: "Hal ini terasa berat sekarang namun sering waktu akan lebih ringan dan lebih mudah.",
        imgUrl: "https://nepho.id/c4omi/img/10.jpg",
    },
    {
        id: 11,
        title: "Segala sesuatu ada hikmahnya",
        body: "Segala sesuatu akan mendatangkan kebaikan bagi kita, ada hikmahnya dan kita akan bersyukur",
        imgUrl: "https://nepho.id/c4omi/img/11.jpg",
    },
    {
        id: 12,
        title: "Saya tidak kuatir akan hidup ini",
        body: "Dunia ini masih tetap stabil. Burung di udara tetap makan. Pasti ada rejeki buat saya",
        imgUrl: "https://nepho.id/c4omi/img/12.jpg",
    },
    {
        id: 13,
        title: "Saya tahu saya dapat melakukan lagi",
        body: "Saya pernah melewati hal-hal seperti ini sebelumnya dan saya tahu saya dapat melakukan lagi.",
        imgUrl: "https://nepho.id/c4omi/img/13.jpg",
    },
    {
        id: 14,
        title: "Saya tahu saya ada di tempat aman",
        body: "Saya tahu bahwa saya ada di tempat yang aman walaupun pikiran saya mengatakan yang sebaliknya.",
        imgUrl: "https://nepho.id/c4omi/img/14.jpg",
    },
    {
        id: 15,
        title: "Saya masih hidup. Saya bersyukur",
        body: "Saya dapat merasakan jantungku berdetak dan kakiku menapak pada lantai. Saya bersyukur masih hidup dan masih OK.",
        imgUrl: "https://nepho.id/c4omi/img/15.jpg",
    },
    {
        id: 16,
        title: "Saya pernah alami yang lebih buruk",
        body: "Saya pernah melewati hal-hal yang lebih buruk dan melewati semua itu dengan aman.",
        imgUrl: "https://nepho.id/c4omi/img/16.jpg",
    },
    {
        id: 17,
        title: "Ini hanya reaksi tubuh",
        body: "Sebenarnya gejolak ini adalah reaksi tubuh terhadap ingatan. Saat ini saya aman.",
        imgUrl: "https://nepho.id/c4omi/img/17.jpg",
    },
    {
        id: 18,
        title: "Adalah OK untuk tidak merasa OK",
        body: "Saya tidak harus merasakan nyaman setiap waktu. Ini membuktikan saya seorang manusia biasa.",
        imgUrl: "https://nepho.id/c4omi/img/18.jpg",
    },
    {
        id: 19,
        title: "Emosi ini akan datang dan pergi",
        body: "Seperti awan di langit, emosi ini akan datang dan pergi. Saya akan merasakan berbeda segera.",
        imgUrl: "https://nepho.id/c4omi/img/19.jpg",
    },
    {
        id: 20,
        title: "Saya mampu bertindak efektif",
        body: "Saya sudah mempunyai keahlian untuk mengatasi situasi ini. Karena itu saya tidak takut",
        imgUrl: "https://nepho.id/c4omi/img/20.jpg",
    },
    {
        id: 21,
        title: "Emosiku tidak akan melukai aku",
        body: "Emosi-emosi yang kualami hanya menyatakan sesuatu. Mereka tidak akan melukai aku.",
        imgUrl: "https://nepho.id/c4omi/img/21.jpg",
    },
    {
        id: 22,
        title: "Tidak ada seorang yang sempurna",
        body: "Saya seorang manusia. Saya dapat berbuat salah. Tidak ada seorangpun yang sempurna. Namun saya dikasihi.",
        imgUrl: "https://nepho.id/c4omi/img/22.jpg",
    },
    {
        id: 23,
        title: "Perlahan-lahan! Perlahan tapi pasti",
        body: "Bertindak perlahan-lahan dan ada lebih dari pilihan yang saya dapat pilih",
        imgUrl: "https://nepho.id/c4omi/img/23.jpg",
    },
    {
        id: 24,
        title: "Saya dapat minta tolong orang lain",
        body: "Saya mahluk sosial dan saya dapat minta tolong orang lain untuk pertolongan.",
        imgUrl: "https://nepho.id/c4omi/img/24.jpg",
    },
    {
        id: 25,
        title: "Membuat keputusan benar",
        body: "Saya pernah membuat keputusan benar. Saya akan terus belajar membuat keputusan yang benar. Saya akan berusaha.",
        imgUrl: "https://nepho.id/c4omi/img/25.jpg",
    },
    {
        id: 26,
        title: "Pikiranku hanyalah pikiran saja",
        body: "Pikiranku adalah hanya sebuah pikiran saja dan tidak selalu benar.",
        imgUrl: "https://nepho.id/c4omi/img/26.jpg",
    },
    {
        id: 27,
        title: "Kebutuhan hidupku akan tercukupi",
        body: "Saya percaya bahwa saya terpelihara dan kebutuhan hidupku pasti tercukupi. Saya tidak kuatir akan hidupku.",
        imgUrl: "https://nepho.id/c4omi/img/27.jpg",
    },
    {
        id: 28,
        title: "Semua akan berlalu",
        body: "Saya tidak takut sebab semua hal buruk pasti berlalu.",
        imgUrl: "https://nepho.id/c4omi/img/28.jpg",
    },
    {
        id: 29,
        title: "Kebaikan akan menang",
        body: "Kebaikan lebih besar dari hal buruk. Kebaikan adalah nilai kekal.",
        imgUrl: "https://nepho.id/c4omi/img/29.jpg",
    },
    {
        id: 30,
        title: "Aku tidak takut dalam berelasi",
        body: "Kasih mengalahkan ketakutan. Aku tidak takut karena aku mengasihi dan dikasihi.",
        imgUrl: "https://nepho.id/c4omi/img/30.jpg",
    },
    {
        id: 31,
        title: "Aku berharga dan bernilai",
        body: "Aku akan bertahan hidup karena hidupku berharga. Aku bersyukur akan hidupku",
        imgUrl: "https://nepho.id/c4omi/img/31.jpg",
    },

];

export default changeperspectivedata;